# Generated by Django 5.2.14 on 2026-06-09 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_name', models.CharField(max_length=200, unique=True)),
                ('components', models.JSONField(help_text='JSON format: [{"product_name": "3-inch stainless hinge", "qty": 2}, {"product_name": "Stainless steel rivet", "qty": 8}]')),
            ],
            options={
                'verbose_name': 'Product BOM',
                'verbose_name_plural': 'Product BOMs',
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Product Master',
                'verbose_name_plural': 'Product Masters',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.CharField(help_text="e.g., 'Customer: John Doe, Date: 2024-01-15'", max_length=200)),
                ('order_qty', models.PositiveIntegerField(default=1)),
                ('legacy_order_id', models.IntegerField(blank=True, help_text='Original order ID from external system', null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='booking.order')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.productbom')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
