# Generated by Django 5.2.14 on 2026-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_productbom_productmaster_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='legacy_order_id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_description',
            field=models.CharField(blank=True, help_text='Auto fill from orders name or you can manual edit such as Customer: John Doe, Date: 2024-01-15', max_length=200),
        ),
    ]
