# Generated by Django 5.2.14 on 2026-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_orderitem_legacy_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('cancelled', '取消'), ('completed', '已完成')], default='pending', max_length=20),
        ),
    ]
